# mise.toml
[tools]
# vercel compatibility
# https://vercel.com/docs/functions/runtimes/node-js/node-js-versions
# https://vercel.com/docs/package-managers
node = "24.20.0"

[settings]
# Read the pnpm version from package.json
idiomatic_version_file_enable_tools = ['pnpm']

[tasks.pnpm-install]
description = 'Installs dependencies with pnpm'
run = 'pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.dev]
description = 'Calls your dev script in `package.json`'
run = 'pnpm run dev'
depends = ['pnpm-install']
