name: CI

on:
  push:

jobs:
  quality:
    name: quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm run eslint

      - name: Check outdated
        continue-on-error: true
        run: pnpm outdated --format list --long >> $GITHUB_STEP_SUMMARY
